sudo: false
language: node_js
cache:
  yarn: true
  directories:
    - node_modules
install:
  - nvm install node
  - node -v
  - npm i -g yarn
  - yarn
  - yarn build
  - yarn run lint
  - yarn run test
node_js:
  - '8'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH=$HOME/.yarn/bin:$PATH
branches:
  only:
    - master
