# Generated by Django 3.0.8 on 2020-07-01 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255, verbose_name='Name')),
                ('image', models.ImageField(upload_to='media/author_images', verbose_name='Image')),
                ('gender', models.CharField(choices=[('mr', 'man'), ('ms', 'woman')], max_length=2, verbose_name='Gender')),
                ('date_of_birthday', models.DateTimeField(verbose_name='Date of birth')),
                ('nationality', models.CharField(max_length=255, verbose_name='Nationality')),
                ('info', models.TextField(verbose_name='Info')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('image', models.ImageField(upload_to='media/category_images', verbose_name='Image')),
                ('description', models.TextField(verbose_name='Description')),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='main.Author', verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('books', models.ManyToManyField(related_name='categories', to='main.Book', verbose_name='Books')),
            ],
        ),
    ]
