# Generated by Django 3.0.7 on 2020-06-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Basligi')),
                ('category', models.IntegerField(choices=[(1, 'Dessert'), (2, 'Food')], verbose_name='Kateqoriya')),
                ('short_description', models.CharField(max_length=255, verbose_name='Qisa Mezmunu')),
                ('image', models.ImageField(upload_to='media/recipes', verbose_name='Sekil')),
                ('long_description', models.TextField(verbose_name='Genis mezmunu')),
                ('author', models.CharField(max_length=50, verbose_name='Muellif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
            ],
        ),
    ]
