# Generated by Django 3.0.7 on 2020-06-30 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to='media/recipes', verbose_name='Sekil'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='long_description',
            field=models.TextField(null=True, verbose_name='Genis mezmunu'),
        ),
    ]
