# Generated by Django 3.0.7 on 2020-06-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20200630_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_view_link',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
