# Generated by Django 3.0.7 on 2020-07-01 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0005_auto_20200630_0844'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
