# Generated by Django 3.0.7 on 2020-07-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_comment_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default=1, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
