# Generated by Django 3.0.7 on 2020-07-07 08:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20200707_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='long_description',
            field=ckeditor.fields.RichTextField(verbose_name='Genis mezmunu'),
        ),
    ]
