# Generated by Django 3.0.7 on 2020-07-08 06:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0014_auto_20200707_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Basligi')),
                ('image', models.ImageField(upload_to='recipes', verbose_name='Sekil')),
                ('long_description', ckeditor.fields.RichTextField(verbose_name='Genis mezmunu')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True, verbose_name='slug')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True, verbose_name='is published')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='stories.Category', verbose_name='Kateqoriya')),
                ('tags', models.ManyToManyField(related_name='stories', to='stories.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Hekaye',
                'verbose_name_plural': 'Hekayeler',
                'ordering': ('-created_at', '-title'),
            },
        ),
    ]
